<h1><b> CREATING THE CLASS CONTAINING ALL THE CLEANING FUNCTIONS </b></h1>

In [ ]:
class nlp_2 :
    
    def __init__(self,n):
        self.n = n
        
    def Cleaning_all(self,text):
        corpus22=[]
            # GENERAL CLEANING
        import nltk
        from nltk.tokenize import sent_tokenize
        import string   
        from nltk.tokenize import word_tokenize
        word_list =  word_tokenize(text)
        from nltk.corpus import stopwords

        #Function to remove stopwords
    
        lang_stopwords = stopwords.words('english')
        stopwords_removed = [w.replace('.','') for w in word_list if w.lower() not in lang_stopwords]
    
        #    " ".join(stopwords_removed)
        
        punt_removed = [w for w in stopwords_removed  if w.lower() not in string.punctuation]
        var1=" ".join(punt_removed)
        var1 = [var1]
        from nltk import PorterStemmer, LancasterStemmer, SnowballStemmer
        from nltk.stem import WordNetLemmatizer
        lemmatizer = WordNetLemmatizer()
        
        #Snowball Stemmer
        
        ss = SnowballStemmer(language='english')
        for w in var1:
            snow = ss.stem(w)
            lem = lemmatizer.lemmatize(snow)
            corpus22.append(lem)
        return corpus22

<h1><b> CREATING THE DATAFRAME </b></h1>


In [2]:
import pandas as pd
import os
os.getcwd()
os.chdir('D:\study\ml\others')
os.getcwd()

'D:\\study\\ml\\others'

In [3]:
df = pd.read_csv('trustpilot_reviews.csv')
df

Unnamed: 0                                               text  sentiment
0              0  Today I went to the Safe zone branch and dealt...          2
1              1  Brian E. Dela Vega of UAE EXCHANGE RAK Al Jaze...          2
2              2  I have been to different exchange but UAE exch...          2
3              3  I would like to thank the fast and accurate se...          2
4              4  Thank' s for the good and fast services it is ...          2
5              5  UAE exchange sajja2 branch provided excellent ...          2
6              6  Thank you Mr. Shinove P for introducing your p...          2
7              7  Had a great experience from emirates headquate...          2
8              8  The staff from this company are very hospital;...          2
9              9  thanks to analiza and kristine of al rigga met...          2
10            10      Excellent Service @ Jebel Ali Parco 2 Branch.          2
11            11  Only Al Ain Alfalfa Plaza UAE Exchange All Sta...          2
12            12  I was a customer of main branch, after Ms cris...          2
13            13  Koshy Thomas is an excellent service provider ...          2
14            14  I take this opportunity as a privilege to shar...          2
15            15  I am a regular customer of UAE Exchange (Sharj...          2
16            16  I made a transaction yesterday in your Al Nahd...          2
17            17  I am a customer for Omanuaexchange and I am ge...          2
18            18  I would like to acknowledge the fast and accur...          2
19            19  Thanks UAE Exchange for an easy and quick tran...          2
20            20  Robins, in safe zone branch he was found good ...          2
21            21  Good Service from Sajja 2 Branch, today I visi...          2
22            22  Veda Shetty handled my transaction very nicely...          2
23            23  To be honest , your branch in Tabarbour is the...          2
24            24  The service was great and the treatment was qu...          2
25            25  Tabarboor branch is great, especially Mutaz wh...          2
26            26  Springs Branch The service level here staff ma...          2
27            27  I went to sajah branch UAE exchange very good ...          2
28            28  Experience with Sanjay of Matajer Juraina and ...          2
29            29  Mr. Nurul Islam is a Very Very good staff in k...          2
...          ...                                                ...        ...
7019        7019  excellent customer services and also giving be...          2
7020        7020                       Excellent customer service!!          2
7021        7021  i recommend UAE Exchange services for everyone...          2
7022        7022  very good service, staff are friendly and help...          2
7023        7023                                 Excellent service.          2
7024        7024  I always use Qatar Uae Exchange for transferri...          2
7025        7025  Sending money to Sri Lanka is easy and fast wi...          2
7026        7026  I send money from Al Sadd branch to my home co...          2
7027        7027  They have flash transfers to India , which is ...          0
7028        7028  UAE Exchange is really good at obtaining first...          2
7029        7029  Its the best remittance company. The customer ...          2
7030        7030  I am always using uaeexchange for all my remit...          2
7031        7031  This is one of the best company in remittance ...          1
7032        7032  I am a customer of UAE Exchange since 12 years...          2
7033        7033  I am a loyal customer of UAE Exchange. I have ...          2
7034        7034  I have been using UAE Exchange for transfer of...          0
7035        7035  I have been using UAE Exchange services for th...          2
7036        7036  The service quality maintained by each and eve...          2
7037        7037  Qatar Uae Exchange played major role i

<h1><b> CALLING THE FUNCTION </b></h1>


In [4]:
a = nlp_2(1)
import nltk
nltk.download('wordnet')
corpus1 = []
for i in range(len(df.index)):
    text = df.iloc[i,1]
    b=a.Cleaning_all(text)
    import re
    review = re.sub('[^a-zA-Z]',' ',str(b))
    corpus1.append(review)
print(corpus1)

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\KIIT\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
['  today went safe zone branch dealt employee rawda hassan send money wester union pleasant deal happily answered inquiri  ', '  brian e dela vega uae exchange rak al jazeera branch    nice kind teller always smiling good see like look like happy job also always ready answer question even busy absolutely good teller branch     ', '  different exchange uae exchange jazeera ras al khaimah gave best treatment clients two thumbs specially mr brian a dela vega patient kind clients friendly yet profession  ', '  would like thank fast accurate service received uae exchange matajer al juraina branch especial mention vanessa feel easy explain fund transfer long takes reflect listens attends queries properly thank uae exchange great servic  ', '  thank good fast services better continue money transaction kind services uae exchange ras al khai

<h1><b> TF-IDF </b></h1>


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
doc_vec1 = vectorizer.fit_transform(corpus1).toarray()
print(doc_vec1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
import numpy as np
x=doc_vec1
y = df.iloc[:,-1].values

In [7]:
from sklearn import model_selection
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.1)  #it splits accordingly without any selection
from sklearn import metrics
from sklearn.metrics import confusion_matrix, classification_report ,accuracy_score
from sklearn import model_selection,neighbors
from sklearn.neighbors import KNeighborsClassifier
model_knn= KNeighborsClassifier()
model_knn.fit(x_train,y_train)
model_knn.score(x_test,y_test)


0.8127659574468085

In [8]:
a22 = nlp_2(1)
corpus3 = []

#for i in range(len(df.index)):

text = 'I have remitted money 4 days back, but the money is not yet credited in my account in India. Upon inquiry, staff did not have any clue about the reason and asked me to wait until they receive a response from their Head Office. I sent money to pay off my loan installment and delay caused me paying additional amount for late charges and interest.'
b=a22.Cleaning_all(text)
review1 = re.sub('[^a-zA-Z]',' ',str(b))
corpus3.append(review1)
print(corpus3)
y_pred1 = model_knn.predict(vectorizer.transform(corpus3).toarray())

['  remitted money   days back money yet credited account india upon inquiry staff clue reason asked wait receive response head office sent money pay loan installment delay caused paying additional amount late charges interest  ']


In [9]:
y_pred1

array([0], dtype=int64)